### ISSUE TITLE
add etymology to words

### ISSUE THREAD

**Issue by amundo** [mixtecnerds/health_in_mixtec#26]
```
-gil
indeterminate motion
etymology:
  etymon: gilli
  etymonGloss: chase
  source: King (2001)
  notes: "The i fell off"
  protoforms: 
    STEDT: gil2 []
    ADFAd: 

```
